### PR TITLE
Fix possible shutdown time bug

### PR DESCRIPTION
**Pull request by ghost**
It should be either "+0" or "now".

From the man page:
> The time string may either be in the format "hh:mm" for hour/minutes specifying the time to execute the shutdown at, specified in 24h clock format. Alternatively it may be in the syntax "+m" referring to the specified number of minutes m from now.  "now" is an alias for "+0", i.e. for triggering an immediate shutdown. If no time argument is specified, "+1" is implied.

Background: I have a strange problem with the WittyPi. The setup works for about five times (boot cycles) and then it gets stuck. I have added this change to my setup in the hope that it will solve the problem. I will keep you informed about the result :)

### CODE REVIEW

**Comment by ghost** [comment]
Unfortunately it did not help. The board is not shutting down correctly. The red indicator light is turned on and the PI board in an halt state. And even after some hours it cannot recover. If anyone has suggestions I am happy to hear them :)

**Comment by elschnorro77** [comment]
> Unfortunately it did not help. The board is not shutting down correctly. The red indicator light is turned on and the PI board in an halt state. And even after some hours it cannot recover. If anyone has suggestions I am happy to hear them :)

Which Raspberry, which WittyPi Versions are you using? Original WittyPi software installed or not? WittyPi not shutting down could also be an issue with communication on the Halt-Pin.

There is also https://www.facebook.com/groups/HoneyPi

**Comment by ghost** [comment]
> > Unfortunately it did not help. The board is not shutting down correctly. The red indicator light is turned on and the PI board in an halt state. And even after some hours it cannot recover. If anyone has suggestions I am happy to hear them :)
> 
> Which Raspberry, which WittyPi Versions are you using? Original WittyPi software installed or not? WittyPi not shutting down could also be an issue with communication on the Halt-Pin.
> 
> There is also https://www.facebook.com/groups/HoneyPi

Pi Zero W with Witty Pi 4. I will have a look at the halt pin thanks!

**Comment by JavanXD** [comment]
@zauberstuhl 
`sudo shutdown -h 0` is not an bug but I'll change it for future versions. 
If you face issues with the latest raspberry image downloaded from GitHub, instead download it from the Download section on our website, the images there are always tested. 

Witty WittyPi I would recommend reading their user guide so you don't use a GPIO for a sensor which is conflicting with a WittyPi GPIO.

**Pull request closed without merging**
