### PR TITLE
Script updates for Virtual UAP0 interface instead of switching of WLAN0 interface

### PR DESCRIPTION
**Pull request by elschnorro77**
- added function for creation of virtual UAP interface
- added sudo for ifup & ifdown as otherwise DHCP Fails on interfaces
- disable hostapd and dnsmasq in shutdown and reboot to prevent autostart on start of pi
- removed start_wlan and stop_wlan as no longer required

- requires also the pull request on HoneyPi to work

(testeted on Pi Zero and Pi 4)

### CODE REVIEW

**Comment by JavanXD** [comment]
Thanks for your PR!
Actually I already made a lot of changes but i did not have time time to test them yet before committing. 
I switched the AccessPoint/Client-Mode switching to `https://github.com/Autodrop3d/raspiApWlanScripts`. What solution would you prefer?
I would like to test both.

**Comment by elschnorro77** [comment]
Hi Javan,

the solution I created the pull request for has both enabled in AP mode
- WLAN (connected to Infrastructure) and AP (with SSID HoneyPi).
Such you are able to update HoneyPi over WLAN using the regular button.

I have my HoneyPi in the garden connected to WLAN and using WLAN
uploading to thingspeak.
Doing updates over the webinterface requried myself always to figure out
the current used DHCP IP. Now I just push the button, connect Tablet to
HoneyPi and update using existing WLAN.

On my Honeypi with Netzclub SIM now I can Share my Handy as AP (and safe
Netzclub data volume) and use the tablet to configure the Pi

Viele Grüße,

Christian

Am 17.01.2020 um 12:44 schrieb Javan Rasokat:

**Comment by cwe6279** [comment]
Realize it is very old but anyone have this working on a Pi with a script notification?  I have a py script via twilio that works from the command line no problem but on install of Honeypi I chose the script option and double checked names and pointers, but seems like no alerts are generated with port scans.    Also, does this perform any install of PSAD?  I don't see anything other than PSAD.conf created if anyone might have gotten something like this working- thanks!

**Comment by JavanXD** [comment]
@cwe6279 you asked your question to the wrong GitHub repo, the honeypot you are referring to is this repo: https://github.com/mattymcfatty/HoneyPi

**Pull request merged**
